<?php

namespace Container2x3DllD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KQuzR5BService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KQuzR5B' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KQuzR5B'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'profilRepository' => ['privates', 'App\\Repository\\ProfilRepository', 'getProfilRepositoryService', true],
        ], [
            'profilRepository' => 'App\\Repository\\ProfilRepository',
        ]);
    }
}
