<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2x3DllD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2x3DllD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2x3DllD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2x3DllD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2x3DllD\App_KernelDevDebugContainer([
    'container.build_hash' => '2x3DllD',
    'container.build_id' => '66ef8f29',
    'container.build_time' => 1604050957,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2x3DllD');
